"""ai agent system

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-07 21:04:43.017041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_run_agent_name', 'agent_run', ['agent_name'], unique=False)
    op.create_index('ix_agent_run_user_created_at', 'agent_run', ['user_id', 'created_at'], unique=False)
    op.create_table('ai_audit_log',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stop_reason', sa.String(length=32), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_audit_log_agent_run_id', 'ai_audit_log', ['agent_run_id'], unique=False)
    op.create_table('ai_recommendation',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_recommendation_agent_run_id', 'ai_recommendation', ['agent_run_id'], unique=False)
    op.create_index('ix_ai_recommendation_user_status', 'ai_recommendation', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###

    # --- ai_audit_log immutability trigger ---
    # Same pattern as migration 0002's audit_log trigger: a hash chain alone
    # only *detects* tampering on demand, it doesn't prevent it. A brand-new
    # table, so no backfill needed -- prev_hash/row_hash are NOT NULL from
    # the start.
    op.execute(
        """
        CREATE FUNCTION reject_ai_audit_log_mutation() RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'ai_audit_log rows are immutable';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER ai_audit_log_no_update BEFORE UPDATE ON ai_audit_log
        FOR EACH ROW EXECUTE FUNCTION reject_ai_audit_log_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER ai_audit_log_no_delete BEFORE DELETE ON ai_audit_log
        FOR EACH ROW EXECUTE FUNCTION reject_ai_audit_log_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER ai_audit_log_no_truncate BEFORE TRUNCATE ON ai_audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION reject_ai_audit_log_mutation();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS ai_audit_log_no_truncate ON ai_audit_log")
    op.execute("DROP TRIGGER IF EXISTS ai_audit_log_no_delete ON ai_audit_log")
    op.execute("DROP TRIGGER IF EXISTS ai_audit_log_no_update ON ai_audit_log")
    op.execute("DROP FUNCTION IF EXISTS reject_ai_audit_log_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_recommendation_user_status', table_name='ai_recommendation')
    op.drop_index('ix_ai_recommendation_agent_run_id', table_name='ai_recommendation')
    op.drop_table('ai_recommendation')
    op.drop_index('ix_ai_audit_log_agent_run_id', table_name='ai_audit_log')
    op.drop_table('ai_audit_log')
    op.drop_index('ix_agent_run_user_created_at', table_name='agent_run')
    op.drop_index('ix_agent_run_agent_name', table_name='agent_run')
    op.drop_table('agent_run')
    # ### end Alembic commands ###
