"""rag knowledge base

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-12 19:48:50.307343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector/pgvector:pg16 ships the extension's files but doesn't enable
    # it in every database by default -- same idempotent-enable pattern as
    # migration 0001's pgcrypto.
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_document',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_document_category', 'rag_document', ['category'], unique=False)
    op.create_index('ix_rag_document_content_hash', 'rag_document', ['content_hash'], unique=True)
    op.create_table('rag_chunk',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_chunk_content_fts', 'rag_chunk', [sa.literal_column("to_tsvector('english', content)")], unique=False, postgresql_using='gin')
    op.create_index('ix_rag_chunk_document_id', 'rag_chunk', ['document_id'], unique=False)
    op.create_index('ix_rag_chunk_embedding_hnsw', 'rag_chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rag_chunk_embedding_hnsw', table_name='rag_chunk', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_rag_chunk_document_id', table_name='rag_chunk')
    op.drop_index('ix_rag_chunk_content_fts', table_name='rag_chunk', postgresql_using='gin')
    op.drop_table('rag_chunk')
    op.drop_index('ix_rag_document_content_hash', table_name='rag_document')
    op.drop_index('ix_rag_document_category', table_name='rag_document')
    op.drop_table('rag_document')
    # ### end Alembic commands ###

    op.execute('DROP EXTENSION IF EXISTS vector')
