"""plaid real integration foundation

Revision ID: 0010
Revises: 0009
Create Date: 2026-07-22 20:23:25.363534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('connector_credential_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_accounts_connector_credential_id',
        'accounts', 'connector_credential', ['connector_credential_id'], ['id'], ondelete='SET NULL',
    )
    op.add_column('connector_credential', sa.Column('institution_name', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('ux_connector_credential_user_provider'), 'connector_credential', type_='unique')
    op.create_unique_constraint('ux_connector_credential_user_item', 'connector_credential', ['user_id', 'provider', 'external_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_connector_credential_user_item', 'connector_credential', type_='unique')
    op.create_unique_constraint(op.f('ux_connector_credential_user_provider'), 'connector_credential', ['user_id', 'provider'], postgresql_nulls_not_distinct=False)
    op.drop_column('connector_credential', 'institution_name')
    op.drop_constraint('fk_accounts_connector_credential_id', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'connector_credential_id')
    # ### end Alembic commands ###
